name: publish

on: [push]

jobs:
  publish-static-website-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u  traynux --password-stdin
        docker build . --tag ghcr.io/traynux/static-website-template:latest
        docker run ghcr.io/traynux/static-website-template:latest
        docker push ghcr.io/traynux/static-website-template:latest
      env:
        CR_PAT: ${{ secrets.CR_PAT }}